"""Type stubs for the SmashTable extension module.

The module is a single C extension with no Python wrapper, so this file is the whole
description a type checker or an editor ever sees. Requires Python 3.12, so the modern
`X | Y` unions and builtin generics are used throughout rather than `typing.Union`.

Each closed set of names the constructors accept is a `Literal`, so a misspelling is a
type error rather than the `ValueError` the parser raises at runtime.
"""

from types import TracebackType
from typing import Any, ClassVar, Iterable, Iterator, Literal, Mapping

__version__: str

# region Names the Constructors Accept

# The key layout a store is built around, which decides how a key is compared and hashed.
_KeyTypeName = Literal["int", "uint", "str", "bytes"]

# Whether a map holds scalars it can store inline, or arbitrary Python objects.
_ValueModeName = Literal["scalar", "object"]

# What a reader is promised, named as Jepsen names it and ordered by strength. The top two
# refuse the same schedules; the stricter one additionally waits for its own publication, so a
# transaction opening after a commit returned cannot be ordered before it.
_IsolationName = Literal["monotonic_atomic_view", "snapshot", "serializable", "strict_serializable"]

# How a store is shared between threads: one lock over the whole store, or a shard per bucket.
_SharingName = Literal["locked", "partitioned"]

# What a store reports it actually delivers, which is wider than what may be asked for: sharding a
# clock-less store falls back to a rung the constructor does not accept.
_DeliveredIsolationName = _IsolationName | Literal["read_committed"]

# A key may be named by its layout or by the Python type standing for it, so `key=int` and
# `key="int"` build the same store. There is no Python type for an unsigned key.
_KeySpec = _KeyTypeName | type[int] | type[str] | type[bytes]

# A value mode may likewise be named by `object` itself rather than by the string.
_ValueSpec = _ValueModeName | type[object]

# Whatever the key layout admits. A store built for one layout refuses the others.
_Key = int | str | bytes

# endregion Names the Constructors Accept

# region Errors

class SmashTableError(Exception):
    """Base of every refusal this module raises, so one `except` catches the family.

    Also raised on its own for a failure no caller can act on, such as a staged version
    missing when a transaction unwound. Retrying one of those cannot help.
    """

class ConflictError(SmashTableError, RuntimeError):
    """Base of the three ways an optimistic validation turns a transaction away.

    Never raised on its own - catch it to retry whichever of the three arrived.
    """

class WriteConflictError(ConflictError):
    """An earlier commit already wrote a key this transaction staged."""

class ReadConflictError(ConflictError):
    """A key this transaction read was committed over before it could commit."""

class PhantomConflictError(ConflictError):
    """A key was committed into a window this transaction had read."""

class DuplicateKeyError(SmashTableError, KeyError):
    """A key was inserted where the caller asked for it to be absent."""

class StateError(SmashTableError, RuntimeError):
    """A transaction was asked for something its current state does not allow."""

# endregion Errors

# region Lazy Views

# Named privately because the module never exports them: they are reached through `keys`, `values`
# and `items`, and `from smashtable import ItemsView` raises `ImportError`.

class _KeysView:
    """A lazy walk over the keys of a sorted map, in key order."""

    @property
    def mapping(self) -> SortedMap:
        """The container this view reads."""

    def __iter__(self) -> Iterator[_Key]: ...
    def __len__(self) -> int: ...

class _ValuesView:
    """A lazy walk over the values of a sorted map, in key order."""

    @property
    def mapping(self) -> SortedMap:
        """The container this view reads."""

    def __iter__(self) -> Iterator[Any]: ...
    def __len__(self) -> int: ...

class _ItemsView:
    """A lazy walk over the pairs of a sorted map, in key order."""

    @property
    def mapping(self) -> SortedMap:
        """The container this view reads."""

    def __iter__(self) -> Iterator[tuple[_Key, Any]]: ...
    def __len__(self) -> int: ...

# endregion Lazy Views

# region Ordered Containers

class SortedMap:
    """An ordered key-value store, kept in key order and transactional at the level asked for."""

    def __init__(
        self,
        *,
        key: _KeySpec,
        value: _ValueSpec = "scalar",
        isolation: _IsolationName = "monotonic_atomic_view",
        sharing: _SharingName = "locked",
    ) -> None: ...
    @property
    def key_type(self) -> _KeyTypeName: ...
    @property
    def value_mode(self) -> _ValueModeName: ...
    @property
    def isolation(self) -> _DeliveredIsolationName: ...
    @property
    def sharing(self) -> _SharingName: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: _Key, /) -> bool: ...
    def __getitem__(self, key: _Key, /) -> Any: ...
    def __setitem__(self, key: _Key, value: Any, /) -> None: ...
    def __delitem__(self, key: _Key | slice, /) -> None: ...
    def __iter__(self) -> Iterator[_Key]: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    # Mutable and compared by content, so it is deliberately unhashable.
    __hash__: ClassVar[None]  # type: ignore[assignment]
    def get(self, key: _Key, default: Any = None, /) -> Any: ...
    def pop(self, key: _Key, default: Any = ..., /) -> Any: ...
    def popmin(self) -> tuple[_Key, Any]: ...
    def setdefault(self, key: _Key, default: Any = None, /) -> Any: ...
    def update(self, other: Mapping[_Key, Any] | Iterable[tuple[_Key, Any]], /) -> None: ...
    def clear(self) -> None: ...
    def scan(
        self, start: _Key | None = None, stop: _Key | None = None, *, limit: int | None = None
    ) -> list[tuple[_Key, Any]]: ...
    def keys(self) -> _KeysView: ...
    def values(self) -> _ValuesView: ...
    def items(self) -> _ItemsView: ...
    def transaction(self) -> Transaction: ...

class SortedSet:
    """An ordered set of members, kept in order and transactional at the level asked for."""

    def __init__(
        self,
        *,
        key: _KeySpec,
        isolation: _IsolationName = "monotonic_atomic_view",
        sharing: _SharingName = "locked",
    ) -> None: ...
    @property
    def key_type(self) -> _KeyTypeName: ...
    @property
    def isolation(self) -> _DeliveredIsolationName: ...
    @property
    def sharing(self) -> _SharingName: ...
    def __len__(self) -> int: ...
    def __contains__(self, member: _Key, /) -> bool: ...
    def __iter__(self) -> Iterator[_Key]: ...
    def __delitem__(self, window: slice, /) -> None:
        """A set is subscripted only by a slice, which erases the window it names."""
    # `__setitem__` exists at runtime only to raise, so it is deliberately absent here: a checker
    # rejecting `members[key] = value` outright is the answer, not a signature that always fails.

    def __repr__(self) -> str: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    # Ordering is subset containment, so only another set answers; an iterable does not.
    def __lt__(self, other: SortedSet | set[_Key] | frozenset[_Key], /) -> bool: ...
    def __le__(self, other: SortedSet | set[_Key] | frozenset[_Key], /) -> bool: ...
    def __gt__(self, other: SortedSet | set[_Key] | frozenset[_Key], /) -> bool: ...
    def __ge__(self, other: SortedSet | set[_Key] | frozenset[_Key], /) -> bool: ...
    # Mutable and compared by content, so it is deliberately unhashable.
    __hash__: ClassVar[None]  # type: ignore[assignment]
    def add(self, member: _Key, /) -> None: ...
    def discard(self, member: _Key, /) -> None: ...
    def remove(self, member: _Key, /) -> None: ...
    def popmin(self) -> _Key: ...
    def update(self, other: Iterable[_Key], /) -> None: ...
    def clear(self) -> None: ...
    def scan(self, start: _Key | None = None, stop: _Key | None = None, *, limit: int | None = None) -> list[_Key]: ...
    def union(self, other: Iterable[_Key], /) -> SortedSet: ...
    def intersection(self, other: Iterable[_Key], /) -> SortedSet: ...
    def difference(self, other: Iterable[_Key], /) -> SortedSet: ...
    def symmetric_difference(self, other: Iterable[_Key], /) -> SortedSet: ...
    def isdisjoint(self, other: Iterable[_Key], /) -> bool: ...
    def transaction(self) -> Transaction: ...

# endregion Ordered Containers

# region Unordered Containers

class HashMap:
    """A key-value store over an open-addressed table, so it keeps no ordering at all."""

    def __init__(
        self,
        *,
        key: _KeySpec,
        value: _ValueSpec = "scalar",
        isolation: _IsolationName = "monotonic_atomic_view",
        sharing: _SharingName = "locked",
    ) -> None: ...
    @property
    def key_type(self) -> _KeyTypeName: ...
    @property
    def value_mode(self) -> _ValueModeName: ...
    @property
    def isolation(self) -> _DeliveredIsolationName: ...
    @property
    def sharing(self) -> _SharingName: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: _Key, /) -> bool: ...
    def __getitem__(self, key: _Key, /) -> Any: ...
    def __setitem__(self, key: _Key, value: Any, /) -> None: ...
    def __delitem__(self, key: _Key, /) -> None: ...
    def __repr__(self) -> str: ...
    def get(self, key: _Key, default: Any = None, /) -> Any: ...
    def pop(self, key: _Key, default: Any = ..., /) -> Any: ...
    def setdefault(self, key: _Key, default: Any = None, /) -> Any: ...
    def update(self, other: Mapping[_Key, Any] | Iterable[tuple[_Key, Any]], /) -> None: ...
    def clear(self) -> None: ...
    def transaction(self) -> Transaction: ...

class HashSet:
    """A set over an open-addressed table, so it keeps no ordering at all."""

    def __init__(
        self,
        *,
        key: _KeySpec,
        isolation: _IsolationName = "monotonic_atomic_view",
        sharing: _SharingName = "locked",
    ) -> None: ...
    @property
    def key_type(self) -> _KeyTypeName: ...
    @property
    def isolation(self) -> _DeliveredIsolationName: ...
    @property
    def sharing(self) -> _SharingName: ...
    def __len__(self) -> int: ...
    def __contains__(self, member: _Key, /) -> bool: ...
    def __repr__(self) -> str: ...
    def add(self, member: _Key, /) -> None: ...
    def discard(self, member: _Key, /) -> None: ...
    def remove(self, member: _Key, /) -> None: ...
    def update(self, other: Iterable[_Key], /) -> None: ...
    def clear(self) -> None: ...
    def transaction(self) -> Transaction: ...

# endregion Unordered Containers

# region Transactions

class Participant:
    """One container's slice of a transaction, reading and writing inside it rather than around it.

    At `serializable` and above a read here is recorded, so the commit can validate it; below that
    nothing is recorded and only `watch` marks a key. A read through the container records nothing at
    any level.
    """

    def __contains__(self, key: _Key, /) -> bool: ...
    def __getitem__(self, key: _Key, /) -> Any: ...
    def __setitem__(self, key: _Key, value: Any, /) -> None: ...
    def __delitem__(self, key: _Key | slice, /) -> None: ...
    def get(self, key: _Key, default: Any = None, /) -> Any: ...
    def add(self, member: _Key, /) -> None: ...
    def discard(self, key: _Key, /) -> bool: ...
    def update(self, other: Mapping[_Key, Any] | Iterable[Any], /) -> None: ...
    def watch(self, key: _Key, /) -> None: ...
    def scan(self, start: _Key | None = None, stop: _Key | None = None, *, limit: int | None = None) -> list[Any]:
        """Reads a window, and at `serializable` and above records it, which is what makes a phantom detectable."""

class Transaction:
    """A group of containers staged together and then published one after another.

    All-or-nothing against failure: a body that raises resets every participant. Publication is not
    one instant, so a concurrent reader may find one container a step ahead of another.
    """

    def begin(self) -> tuple[Participant, ...]: ...
    def stage(self) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def reset(self) -> None: ...
    def __enter__(self) -> tuple[Participant, ...]: ...
    def __exit__(
        self,
        exception_type: type[BaseException] | None,
        exception: BaseException | None,
        traceback: TracebackType | None,
    ) -> bool | None: ...

def transaction(*stores: SortedMap | SortedSet | HashMap | HashSet) -> Transaction:
    """Opens one transaction spanning every store named, which commits as a single unit."""

# endregion Transactions
